### PR TITLE
added duplicate_braces.c++.

### PR DESCRIPTION
**Pull request by mahimonga**
added duplicate_braces.c++ with a problem statement in brief along with my solution to it.
#hacktoberfest

### CODE REVIEW

**Comment by mahimonga** [comment]
please accept pull request with hacktober tags.

**Comment by mahimonga** [comment]
@God-father1 please merge this with hacktober labels. Thank you in advance.Happy hacking!

**Comment by mahimonga** [comment]
> @mahimonga there is no need to accept the PR as hacktober tags. If your PR gets merged then be counted towards hacktoberfest. Please don't promote such irrelevant updates.
image
@God-father1 on https://hacktoberfest.digitalocean.com/profile page it says something like as shown in the figure. My previous prs were not counted because of this reason they said this when I contacted their support. That's why I said :
>@God-father1 please merge this with hacktober labels. Thank you in advance.Happy hacking!
Please correct me if I am wrong or misunderstood something. Constructive criticism is always welcome. And tell me if something is wrong with my pr. Have a great day ahead! Happy hacking! 
Thanks in advance.

**Comment by God-father1** [comment]
@mahimonga  Our repository has `Hacktoberfest` topic and every PR is getting counted for the hacktoberfest may it be before 3rd October or after that so relax and wait for your PR to get mature  😃

**Comment by mahimonga** [comment]
@God-father1 thank you so much for explaining to me and clearing my misunderstanding. Have a great day :)

**Comment by mahimonga** [comment]
@God-father1 Sorry for pinging you again but can you merge my pr? If there are any changes you would like to change please inform me. Have a great day ahead!

**Pull request merged**
